export const musicAboutText = {
  p1: "Jacob Silver is a grammy-nominated and oscar-winning bassist (upright and electric), but also works as a recording engineer, producer, composer, and booking agent. He owns Media Blitz Record Co., a record label that specializes in vinyl records. He is the principal booker for two prominent music venues in Brooklyn NY: Pete's Candy Store and Pine Box Rock Shop.  He has performed or collaborated with many prominent and award-winning musicians, including Pete Seeger, Arlo Guthrie, Levon Helm's Midnight Ramble Band, Bob Weir, Patti Griffin, Lucinda Williams, Natalie Merchant, Kate Pierson (of The B52's), Charles Bradley, The Mammals, Andrew Bird, Lauryn Hill, Lee Fields and The Expressions, Emmylou Harris, Gary Karr, Rushad Eggleston, Mike + Ruthy, Christina Courtin, Aoife O'Donovan, and Tao Rodriquez-Seeger, among others.",
  p2: "Silver studied music at the Berklee College of Music, the San Francisco Conservatory of Music, and the University of Victoria. He studied the double bass with famed classical bassist Gary Karr.",
  p3: "After completing his studies in 2002, Silver moved to New York. In 2008 he recorded, performed, and co-produced the album, “Let There Be Peace On Earth, and Let It Begin With Me”, a collection of children’s songs written by Jill Jackson and Sy Miller. In 2009 he played in Pete Seeger’s 90th birthday celebration at Madison Square Garden, accompanying such musical legends as Taj Mahal, Emmylou Harris, Bruce Springsteen, Tom Paxton, Steve Earle, Tommy Sands, The McGarrigle Sisters, Rufus and Martha Wainwright, Dave Matthews, and more. Silver also appears on the album, “Preservation: An album benefitting Preservation Hall and the Preservation Hall Music Outreach Program”, where he plays bass with the legendary Preservation Hall Jazz Band. He also appeared in the film “20 Feet from Stardom”, where he plays with some of the most recorded singers in history. ",
};
export const codeAboutText = {
  p1: "Jacob Silver a full stack web developer, with a focus on React-specific projects, along with experience with JavaScript, HTML, CSS, and AppleScript. Booking over 200 concerts a month while remaining extremely busy as a self-employed musician inspired him to develop his own software and automation solutions, which led him to pursue a career in web development. He has strong skills in project management, automation, and workflow planning. He has years of experience creating and managing workflows for entire teams to manage the complexities of a music venue.",
  p2: "He is currently employed by Tempo Software.",
};
